[workspace]

members = [
    "helloworld-tonic",   # tonic hello world
    "routeguide-tonic",   # tonic route guide
    "tshooter",
    "roguelike-tutorial",
    "leetcode",
    "xdiff",
    "ys",
    "exercism",
    "mike",
]
